import React from "react";
import Layout from "../components/layout";
import Head from "next/head";

const Register = () => {
  return (
    <Layout>
      <Head>
        <title>SOOMIN`s PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dev.png" />
      </Head>
      <div></div>
    </Layout>
  );
};

export default Register;
